@startuml "MiraVeja - Components Diagram"
!theme plain

title MiraVeja - Components Diagram

' Components
package Acquisition as acquisition #LightBlue {
    [Image Provider] as imageProvider
    [Image Downloader] as imageDownloader
    [Metadata Parser] as metadataParser
}

package Processing as processing #LightGreen {
    [Image Processor] as imageProcessor
    [Embeddings Generator] as embeddingsGenerator
}

package Storage as storage #LightYellow {
    [Database] as database
    [File System] as fileSystem
    [Encyption] as encryption
}

package Retrieval as retrieval #LightCoral {
    [Image Content Retriever] as imageContentRetriever
    [Metadata Retriever] as metadataRetriever
    [Embeddings Search] as embeddingsSearch
}

' Relationships
imageProvider --> imageDownloader : "Provides images' metadata and content"
metadataParser <--> imageDownloader : "Cleans up image metadata"
imageDownloader .r.> database : "Saves images' metadata"
imageDownloader .r.> fileSystem : "Saves images' content"

imageProcessor .u.> fileSystem : "Saves images' thumbnails"
embeddingsGenerator .u.> database : "Saves images' embeddings"

imageContentRetriever <.d.> fileSystem : "Retrieves images' content"
metadataRetriever <.d.> database : "Retrieves images' metadata"
embeddingsSearch <.d.> database : "Searches images' embeddings"

fileSystem <..> encryption : "(De)Encrypts the image content"

@enduml