name: 🧪 MiraVeja CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  API_DIRECTORY: api
  PYTHON_VERSION: 3.13

jobs:
  # 🧪 Unit Tests
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.API_DIRECTORY }}/requirements.txt

      - name: Run tests
        run: |
          pytest ${{ env.API_DIRECTORY }}/tests/unit --disable-warnings -q